const SUPABASE_URL = 'https://uovppzmlwkqgpvznipzu.supabase.co';
const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvdnBwem1sd2txZ3B2em5pcHp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MjgzMDYsImV4cCI6MjA2NTAwNDMwNn0.MbahXodbWZ7jUziYJQtg8hLt3l-P0M7wKZQJC7-QR70';
const supabase = supabase.createClient(SUPABASE_URL, SUPABASE_KEY);
